import type { Metadata } from "next";
import { Inter, Inter_Tight, Tiny5 } from "next/font/google";
import "./globals.css";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

const interTight = Inter_Tight({
    variable: "--font-inter-tight",
    subsets: ["latin"],
});

const jersey10 = Tiny5({ variable: "--font-jersey-10", weight: "400" });

export const metadata: Metadata = {
    title: "hackaplace",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.variable} ${interTight.variable} ${jersey10.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
